version: '3.3'

services:
    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"

    kafka:
        image: wurstmeister/kafka:latest
        ports:
            - "9092:9092"
        environment:
            KAFKA_BROKER_ID: 1
            # Topic 1 will have 1 partition and 3 replicas, Topic 2 will have 1 partition, 1 replica and a cleanup.policy set to compact
            #KAFKA_CREATE_TOPICS: "topic_bench_go:1:3,topic_bench_php:1:3:compact"
            KAFKA_CREATE_TOPICS: "topic_bench_go:1:3,topic_bench_php:1:3"
            KAFKA_ADVERTISED_HOST_NAME: 192.168.99.101
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    kafka2:
        image: wurstmeister/kafka:latest
        ports:
            - "9093:9092"
        environment:
            KAFKA_BROKER_ID: 2
            KAFKA_ADVERTISED_HOST_NAME: 192.168.99.101
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        links:
          - kafka

    kafka3:
        image: wurstmeister/kafka:latest
        ports:
            - "9094:9092"
        environment:
            KAFKA_BROKER_ID: 3
            KAFKA_ADVERTISED_HOST_NAME: 192.168.99.101
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        links:
          - kafka2

    golang:
        build: ./docker/golang
        volumes:
            - "./producer/go:/app"

    php71-cli:
        build: ./docker/php71-cli
        volumes:
          - "./producer/php:/app"
